apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: external-secrets-operator.fling.vsphere.vmware.com
spec:
  categories:
  - CI/CD
  - GitOps
  displayName: external-secrets-operator
  iconSVGBase64: none
  longDescription: external-secrets-operator is used to deploy instance of .....
  maintainers:
  - name: First
  - name: Second
  - name: Third
  providerName: VMware
  shortDescription: external-secrets-operator is used to deploy ....
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: external-secrets-operator.fling.vsphere.vmware.com.0.9.12
spec:
  refName: external-secrets-operator.fling.vsphere.vmware.com
  releasedAt: "2024-02-12T18:59:13Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: harbor.navneet.pro/library/external-secrets-operator@sha256:7578cb6444f9775c378a83ac364fdf115c849952c41ae3e37313b336ae3bb029
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.9.12
