# Before starting create a secret with the required configurations. 
#kubectl create secret generic gcpsm-secret --from-file=secret-access-credentials=key.json -n demo1
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: pa-nverma
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager
  target:
    name: workload-vsphere-tkg2-ssh
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .mysecret | toString }}"
  data:
  - secretKey: mysecret
    remoteRef:
      key: tkg-ssh-priv-keys