#kubectl create secret generic gcpsm-secret --from-file=secret-access-credentials=key.json -n demo1
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: demo1
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: pa-nverma
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
  namespace: demo1
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager
  target:
    name: my-secret
  data:
  - secretKey: my-key
    remoteRef:
      key: kubernetes-cluster
